# Generated by Django 3.0.5 on 2020-04-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('card_charges', models.IntegerField()),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
            ],
        ),
    ]
