# Generated by Django 3.0.5 on 2020-04-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('outpatients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=300)),
                ('temperature', models.CharField(max_length=300)),
                ('bp', models.DateField()),
                ('pr', models.IntegerField()),
                ('rr', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=300)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
            ],
        ),
    ]
