# Generated by Django 3.0.5 on 2020-05-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0002_vitalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalinfo',
            name='bp',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vitalinfo',
            name='pr',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='vitalinfo',
            name='weight',
            field=models.CharField(max_length=300),
        ),
    ]
