# Generated by Django 3.0.5 on 2020-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0004_auto_20200502_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient',
            name='triage',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
