# Generated by Django 3.0.5 on 2020-05-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('outpatients', '0006_auto_20200502_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complains', models.CharField(max_length=300)),
                ('history', models.CharField(max_length=300)),
                ('examination', models.CharField(max_length=300)),
                ('lab_investigation', models.CharField(max_length=300)),
                ('diagnosis', models.CharField(max_length=300)),
                ('doc_notes', models.CharField(max_length=300)),
                ('next_review', models.DateField()),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_treatment', to='outpatients.Outpatient')),
            ],
        ),
    ]
