# Generated by Django 3.0.5 on 2020-05-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('outpatients', '0007_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalinfo',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='treated_by', to='users.UserProfile'),
        ),
    ]
