# Generated by Django 3.0.5 on 2020-05-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0008_vitalinfo_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='triage',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
