# Generated by Django 3.0.5 on 2020-05-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('outpatients', '0009_auto_20200505_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_no', models.CharField(max_length=300)),
                ('card_no', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('card_charges', models.IntegerField()),
                ('pat_cat', models.CharField(max_length=300)),
                ('blood_group', models.CharField(max_length=300)),
                ('marital_status', models.CharField(max_length=300)),
                ('known_allergy', models.CharField(max_length=300)),
                ('kin', models.CharField(max_length=300)),
                ('kin_relationship', models.CharField(max_length=300)),
                ('admitted_at', models.DateField(auto_now=True)),
                ('admitted_by', models.CharField(max_length=300)),
                ('casulty', models.CharField(max_length=300)),
                ('old_patient', models.CharField(max_length=300)),
                ('insurance', models.CharField(max_length=300)),
                ('credit_limit', models.CharField(max_length=300)),
                ('bed_group', models.CharField(max_length=300)),
                ('bed_no', models.CharField(max_length=300)),
                ('discharged', models.CharField(max_length=300)),
                ('discharged_at', models.CharField(max_length=300)),
                ('triage', models.BooleanField(blank=True, default=True)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_treatment', to='outpatients.Patient'),
        ),
        migrations.AlterField(
            model_name='vitalinfo',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_vitals', to='outpatients.Patient'),
        ),
        migrations.DeleteModel(
            name='Outpatient',
        ),
    ]
