# Generated by Django 3.0.5 on 2020-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0011_auto_20200511_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitted_at',
            field=models.DateField(),
        ),
    ]
