# Generated by Django 3.0.6 on 2020-05-23 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('outpatients', '0012_auto_20200511_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('status', models.IntegerField(blank=True, default=1)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_category', to='outpatients.PatCategory'),
        ),
    ]
