# Generated by Django 3.0.6 on 2020-05-23 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0013_auto_20200523_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='kin_contact',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
