# Generated by Django 3.0.6 on 2020-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0014_patient_kin_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='kin_contact',
            field=models.IntegerField(max_length=11),
        ),
    ]
