# Generated by Django 3.0.2 on 2020-03-11 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=300)),
                ('cpm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.FloatField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=300)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iamadmin.Company')),
                ('modules', models.ManyToManyField(related_name='package', to='iamadmin.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('status', models.CharField(default='Unpaid', max_length=300)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='iamadmin.Subscriptions')),
            ],
        ),
    ]
