# Generated by Django 3.0.2 on 2020-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamadmin', '0002_billing_modules_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(default='Active', max_length=300),
        ),
    ]
