# Generated by Django 2.2.6 on 2020-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamadmin', '0004_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='package',
            field=models.ManyToManyField(related_name='company_packages', to='iamadmin.Package'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='modules',
            field=models.ManyToManyField(related_name='company_modules', to='iamadmin.Modules'),
        ),
    ]
