# Generated by Django 2.2.6 on 2020-05-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamadmin', '0005_auto_20200507_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='email@company.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(default='254', max_length=300),
        ),
    ]
