# Generated by Django 3.0.5 on 2020-05-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone_call_log',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
