# Generated by Django 3.0.5 on 2020-05-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_auto_20200505_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complainz_type', to='frontoffice.Complain_type'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='complain_source', to='frontoffice.Source'),
        ),
        migrations.AlterField(
            model_name='equiry',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equiry_ref', to='frontoffice.Reference'),
        ),
        migrations.AlterField(
            model_name='equiry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='equiry_source', to='frontoffice.Source'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitor_purpose', to='frontoffice.Purpose'),
        ),
    ]
