# Generated by Django 2.2.6 on 2020-03-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pm', '0001_initial'),
        ('hr', '0022_auto_20200327_0941'),
        ('iamadmin', '0003_auto_20200312_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateTimeField()),
                ('ending', models.DateTimeField()),
                ('generated_on', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=300)),
                ('approvals', models.ManyToManyField(blank=True, related_name='approved_by', to='hr.Employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iamadmin.Company')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr.Employee')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_hours', models.FloatField()),
                ('extra_hours', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_payslip', to='hr.Employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance.Payroll')),
            ],
        ),
    ]
