# Generated by Django 2.2.6 on 2020-03-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamadmin', '0003_auto_20200312_1510'),
        ('pm', '0001_initial'),
        ('hr', '0027_auto_20200328_0702'),
        ('finance', '0003_auto_20200328_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='extra_hours',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='normal_hours',
        ),
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('spent', models.FloatField(blank=True, default=0.0)),
                ('date_disbursed', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='petty_cash', to='iamadmin.Company')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_by', to='hr.Employee')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_cash', to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('change', models.FloatField(blank=True, default=0.0)),
                ('expense_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('receipt_scan', models.ImageField(blank=True, upload_to='expense')),
                ('cash_lot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_cash', to='finance.PettyCash')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='c_expenses', to='iamadmin.Company')),
                ('expense_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_by', to='hr.Employee')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expense_rec_by', to='hr.Employee')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_expenses', to='pm.Workstation')),
            ],
        ),
    ]
