# Generated by Django 2.2.6 on 2020-03-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20200330_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='status',
            field=models.CharField(default='Pending', max_length=300),
        ),
    ]
