# Generated by Django 2.2.6 on 2020-03-31 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_auto_20200328_0702'),
        ('finance', '0005_payslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='employee_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payroll_em_type', to='hr.EmployeeType'),
            preserve_default=False,
        ),
    ]
