# Generated by Django 3.0.6 on 2020-05-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payslip_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='name',
            field=models.CharField(max_length=330),
        ),
    ]
