# Generated by Django 3.0.6 on 2020-05-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20200524_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranch',
            old_name='name',
            new_name='branchname',
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_branch', to='finance.Bank'),
        ),
    ]
