# Generated by Django 3.0.6 on 2020-05-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20200524_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankbranch',
            old_name='branchname',
            new_name='name',
        ),
    ]
