# Generated by Django 3.0.2 on 2020-02-19 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uzer_settings', '0001_initial'),
        ('iamadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_branch', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('email', models.CharField(default='user@mail.com', max_length=200)),
                ('leaves', models.CharField(default=1, max_length=200)),
                ('kra_pin', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=200)),
                ('employment_date', models.CharField(max_length=200)),
                ('expiry_date', models.CharField(max_length=200)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateTimeField(auto_now=True)),
                ('startdate', models.CharField(blank=True, max_length=250)),
                ('enddate', models.CharField(blank=True, max_length=250)),
                ('leave_type', models.CharField(blank=True, default='unpaid', max_length=200)),
                ('request_notes', models.CharField(blank=True, default='Not Available', max_length=300)),
                ('notes', models.CharField(blank=True, default='Not available', max_length=300)),
                ('status', models.CharField(blank=True, default='pending', max_length=50)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uzer_settings.LeaveType')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleaves', to='hr.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hr.EmployeeType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='workstation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pm.Workstation'),
        ),
    ]
