# Generated by Django 3.0.2 on 2020-03-16 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0012_auto_20200313_1119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iamadmin', '0003_auto_20200312_1510'),
        ('uzer_settings', '0003_auto_20200220_0757'),
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_type', models.CharField(max_length=300)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='categories', to='fleet.FleetCategory')),
            ],
        ),
        migrations.CreateModel(
            name='FuelReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_name', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, default=0, max_length=200)),
                ('status', models.CharField(blank=True, default='active', max_length=200)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
                ('workstation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='site_reserves', to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=200)),
                ('vmodel', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('insurance_expiry', models.DateField()),
                ('inspection_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=200)),
                ('insurance_scan', models.FileField(blank=True, upload_to=fleet.models.insurance_folder)),
                ('image', models.ImageField(blank=True, upload_to=fleet.models.fleet_photo_folder)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='company_fleet', to='iamadmin.Company')),
                ('driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hr.Employee')),
                ('fleet_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='types', to='fleet.FleetType')),
            ],
        ),
        migrations.CreateModel(
            name='FuelReserveRefill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=200)),
                ('unit_price', models.CharField(max_length=200)),
                ('supplier', models.TextField(max_length=300)),
                ('refill_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
                ('recieved_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('reserve', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fleet.FuelReserve')),
                ('workstation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='siterefills', to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='FuelLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=300)),
                ('issued', models.CharField(max_length=300)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
                ('item', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uzer_settings.StockItem')),
                ('workstation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='site_fuel_levels', to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='FuelIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('reciept', models.CharField(blank=True, max_length=300)),
                ('capacity', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateTimeField(auto_now=True)),
                ('reciept_image', models.ImageField(blank=True, upload_to=fleet.models.fuel_reciept_folder)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
                ('issued_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='machines', to='fleet.Machinery')),
                ('reserve', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fleet.FuelReserve')),
                ('workstation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sitefuel', to='pm.Workstation')),
            ],
        ),
        migrations.CreateModel(
            name='FuelBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField()),
                ('available', models.FloatField()),
                ('used_up', models.CharField(default='No', max_length=20)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='iamadmin.Company')),
                ('delivery', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='fleet.FuelReserveRefill')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='uzer_settings.StockItem')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pm.Workstation')),
            ],
        ),
    ]
