# Generated by Django 2.2.6 on 2020-03-26 05:03

from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelissue',
            name='ordometer',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelissue',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelissue',
            name='supplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelissue',
            name='work_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelissue',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelissue',
            name='capacity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuelissue',
            name='reciept',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fuelissue',
            name='reciept_image',
            field=models.ImageField(blank=True, null=True, upload_to=fleet.models.fuel_reciept_folder),
        ),
        migrations.AlterField(
            model_name='fuelissue',
            name='reserve',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='fleet.FuelReserve'),
        ),
    ]
