# Generated by Django 2.2.6 on 2020-03-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20200326_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelissue',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.FuelReserve'),
        ),
    ]
