# Generated by Django 2.2.6 on 2020-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20200326_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelreserverefill',
            name='capacity',
        ),
        migrations.AddField(
            model_name='fuelreserverefill',
            name='amount',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelreserverefill',
            name='available',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelreserverefill',
            name='used_up',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='fuelreserve',
            name='capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fuelreserve',
            name='level',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.DeleteModel(
            name='FuelBatch',
        ),
    ]
