# Generated by Django 2.2.6 on 2020-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20200326_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreserverefill',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
