# Generated by Django 2.2.6 on 2020-03-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_fuelreserverefill_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelissue',
            old_name='capacity',
            new_name='quantity',
        ),
    ]
