# Generated by Django 3.0.5 on 2020-04-29 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('inventory', '0003_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=300)),
                ('supplier', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=300)),
                ('generic_name', models.CharField(max_length=300)),
                ('Strength', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('uom', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('qty_on_hand', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('markup_price', models.IntegerField()),
                ('expiry', models.DateField()),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserProfile')),
            ],
        ),
    ]
