# Generated by Django 3.0.5 on 2020-05-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200503_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Brand_item', to='inventory.Brands'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cat_item', to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='items',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Uom_item', to='inventory.Uom'),
        ),
    ]
