# Generated by Django 3.0.2 on 2020-02-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0008_auto_20200221_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=300)),
                ('ndate', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(to='hr.Employee')),
            ],
        ),
    ]
