# Generated by Django 3.0.2 on 2020-02-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iamadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='company_projects', to='iamadmin.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='company_sites', to='iamadmin.Company')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_sites', to='pm.CompanyProject')),
            ],
        ),
    ]
