# Generated by Django 2.2.6 on 2020-04-01 07:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_auto_20200328_0702'),
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyproject',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstation',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_creator', to='hr.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
