# Generated by Django 2.2.6 on 2020-04-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20200401_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='status',
            field=models.CharField(default='Active', max_length=300),
        ),
    ]
