# Generated by Django 2.2.6 on 2020-04-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_auto_20200401_0846'),
        ('iamadmin', '0003_auto_20200312_1510'),
        ('uzer_settings', '0005_auto_20200327_0948'),
        ('pm', '0003_workstation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('other_title', models.TextField(blank=True, null=True)),
                ('contract_no', models.CharField(max_length=330)),
                ('contingency', models.FloatField(blank=True, default=0)),
                ('date_created', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_boqs', to='iamadmin.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_creator', to='hr.Employee')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_boq', to='pm.CompanyProject')),
            ],
        ),
        migrations.CreateModel(
            name='BoqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=330)),
                ('description', models.TextField()),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_items', to='pm.Boq')),
            ],
        ),
        migrations.CreateModel(
            name='BoqMainItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=330)),
                ('description', models.TextField()),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_main_item', to='pm.BoqItem')),
            ],
        ),
        migrations.CreateModel(
            name='BoqSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=330)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('boq_main_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_sub_item', to='pm.BoqMainItem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_sub_item_unit', to='uzer_settings.ItemUnit')),
            ],
        ),
    ]
