# Generated by Django 2.2.6 on 2020-04-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_boq_boqitem_boqmainitem_boqsubitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqsubitem',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='boq_sub_items', to='pm.Boq'),
            preserve_default=False,
        ),
    ]
