# Generated by Django 2.2.6 on 2020-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_boq_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
