# Generated by Django 2.2.6 on 2020-04-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_boq_last_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoqMainItem',
            new_name='BoqItemClass',
        ),
    ]
