# Generated by Django 2.2.6 on 2020-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_auto_20200411_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='vat',
            field=models.FloatField(blank=True, default=16),
        ),
    ]
